
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Add Product',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
 
        <main style={{marginTop:'20px',background:'#fff',width:'500px',height:'0px'}}> {children}</main>
       
        </body>
    </html>
  )
}
