import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClientProvider } from '@/Redux/ClientProvider'
import { Outfit } from 'next/font/google'

const inter = Outfit({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Tessam',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProvider >
        <main >{children}</main>
        </ClientProvider>
        </body>
    </html>
  )
}
